version: '3'
services:
    # External Dependencies
    mysql:
        container_name: ${COMPOSE_PROJECT_NAME}_mysql
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: weco
        ports:
            - '3306:3306'
